package com.morseling.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val LightPrimary = Color(0xFF1A6BA0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCFE5FF)
val LightOnPrimaryContainer = Color(0xFF001D33)
val LightSecondary = Color(0xFF526070)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD5E4F7)
val LightOnSecondaryContainer = Color(0xFF0E1D2A)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF3DAFF)
val LightOnTertiaryContainer = Color(0xFF251431)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7F9FF)
val LightOnBackground = Color(0xFF181C20)
val LightSurface = Color(0xFFF7F9FF)
val LightOnSurface = Color(0xFF181C20)
val LightSurfaceVariant = Color(0xFFDEE3EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightSurfaceContainerHighest = Color(0xFFE2E2E8)
val LightSurfaceContainerHigh = Color(0xFFE7E7EE)
val LightSurfaceContainer = Color(0xFFEDEDF3)
val LightSurfaceContainerLow = Color(0xFFF3F3F9)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)

// Dark scheme
val DarkPrimary = Color(0xFF98CCFF)
val DarkOnPrimary = Color(0xFF003354)
val DarkPrimaryContainer = Color(0xFF004C77)
val DarkOnPrimaryContainer = Color(0xFFCFE5FF)
val DarkSecondary = Color(0xFFBAC8DB)
val DarkOnSecondary = Color(0xFF243240)
val DarkSecondaryContainer = Color(0xFF3A4857)
val DarkOnSecondaryContainer = Color(0xFFD5E4F7)
val DarkTertiary = Color(0xFFD7BDE4)
val DarkOnTertiary = Color(0xFF3B2948)
val DarkTertiaryContainer = Color(0xFF523F5F)
val DarkOnTertiaryContainer = Color(0xFFF3DAFF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF101418)
val DarkOnBackground = Color(0xFFE1E2E8)
val DarkSurface = Color(0xFF101418)
val DarkOnSurface = Color(0xFFE1E2E8)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkSurfaceContainerHighest = Color(0xFF32353B)
val DarkSurfaceContainerHigh = Color(0xFF282A30)
val DarkSurfaceContainer = Color(0xFF1E2025)
val DarkSurfaceContainerLow = Color(0xFF1A1C21)
val DarkSurfaceContainerLowest = Color(0xFF0B0E13)
